### ISSUE TITLE
[BUG] - Search Tab not working on indices that contains an id field of type Object

### ISSUE THREAD

**Issue by maurin-at-homiwoo** [cars10/elasticvue#142]
**Description**
The search view display `No entries found` when the indices contains a field named `id` that is an object. 

In the console there the following error 
```
Error: Cannot convert object to primitive value
    at o.isSelected (chunk-vendors.092c7a44.js:66:60509)
    at chunk-vendors.092c7a44.js:66:58436
    at Array.some (<anonymous>)
    at o.someItems (chunk-vendors.092c7a44.js:66:58423)
    at t.get (chunk-vendors.092c7a44.js:14:25094)
    at t.evaluate (chunk-vendors.092c7a44.js:14:26094)
    at o.someItems (chunk-vendors.092c7a44.js:14:39730)
    at o.genHeaders (chunk-vendors.092c7a44.js:59:466720)
    at o.genDefaultScopedSlot (chunk-vendors.092c7a44.js:59:472471)
    at Object.s [as default] (chunk-vendors.092c7a44.js:14:17648)
```
When debuging, we can see that isSelected is trying to get a primitive for the id field on the row : 
```  
isSelected(t) {
                    return !!this.selection[Object(h["o"])(t, this.itemKey)] || !1
                }
```

**Steps To Reproduce**
List the steps to reproduce your problem:
1. Create an indice with an id field in the source, this field should be an object with multiple fields
You can use this post in _bulk to do so : 
```
{ "index" : { "_index" : "test_id", "_id" : "1" } }
{ "id" : { "blip": "1", "blap": "2"}, "blop": "Blup" }
{ "index" : { "_index" : "test_id", "_id" : "2" } }
{ "id" : { "blip": "12", "blap": "22"}, "blop": "Blup3" }
{ "index" : { "_index" : "test_id", "_id" : "3" } }
{ "id" : { "blip": "13", "blap": "23"}, "blop": "Blup3" }
```
3. Look for the index test_id in the Indices tab, it should have 3 records
4. Open it with the magnifier button to open the search tab, you'll have No entries found and the error in the console.

**Environment (please include the following information):**
* Elasticsearch version: 8.4
* Operating system: Ubuntu 22.04
* Browser + version: Chrome  112.0.5615.165
* Elasticvue version: 0.44
* How are you running elasticvue? (docker, browser extension, web app): Browser Extension

**Comment by cars10** [comment]
I cannot reproduce this issue. How do you even create a document with an id object? Your provided bulk example also does not work, the documents are not indexed correctly. Do you have more information for this?

**Comment by maurin-at-homiwoo** [comment]
Hi, thanks for coming back to me for that. 

Here is the way I'm indexing the documents : 
![image](https://github.com/cars10/elasticvue/assets/96076076/c15e4c26-69e3-4aea-8c29-0c258a81b5da)

And that's the search screen results 
![image](https://github.com/cars10/elasticvue/assets/96076076/7e6c4e04-16f0-4fbd-8389-c6b6445a9120)

And when I'm doing a rest query : 
![image](https://github.com/cars10/elasticvue/assets/96076076/ee5ab995-bebe-4304-88a2-d4c261dc84e3)

My elastic node is a local node running in docker, here are the info from the first screen : 
![image](https://github.com/cars10/elasticvue/assets/96076076/4ead8acc-ea5e-4b0d-9feb-db35239d4722)


So not sure how I can help you debug that. Let me know if I can do anything else that can help you (maybe an elasticdump dump of the index ? ).

**Comment by cars10** [comment]
Thanks :) I can reproduce the issue when using your provided `_bulk´ body on an elasticsearch 7.x cluster. Seems like it doesn't work on 8.x (this is also visible in your screenshot, the bulk response shows numerical ids and not the ones you provided). I will see if i can fix it.

**Comment by maurin-at-homiwoo** [comment]
Yes, for the id, that's expected, I provide a numerical id for the "_id" field, and another object for the "id" field without underscore. 

The actual id used by elasticsearch is "_id" (in our usecase, it's sometime an id generated by elasticsearch, sometime a string we provide), and we have another field named "id" (which I agree is awful and terrible, but you now, legacy code xD), and it's this `id` field that seems to break elasticvue.

**Comment by cars10** [comment]
This will be fixed in the upcoming beta version of elasticvue :)
![image](https://github.com/cars10/elasticvue/assets/4118628/92a9baff-b31e-40b4-ab4d-54812ffe7df4)

**Comment by maurin-at-homiwoo** [comment]
Yeaye ! Thanks a lot, that's great ! :D :partying_face: :+1: :man_dancing: (and congrats for the quick fix, that was really fast :D )
